name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # 의존성 설치
  install-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Cheeckout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore node_modules from Cache
        id: restore-node-modules
        uses: actions/cache@v3
        with:
          path: week-3/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('week-3/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node

      - name: Install Dependencies

  # lint 확인 및 수정
  lint:

  # 테스트 검증
  test:

  # React Build
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
          npx webpack
